---

- name: restart datadog-agent
  service:
    name: datadog-agent
    state: restarted
  when: datadog_enabled and not ansible_check_mode

- name: restart DatadogAgent
  win_service:
    name: DatadogAgent
    state: restarted
  when: datadog_enabled and not ansible_check_mode